name: Ilona Hassan Bridal Lingerie
favicon: null
layout_spectrum: 0.88598
typography_spectrum: 0.8138280452694744
title: Ilona Hassan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e9eadd'
    - '#697a8f'
    - '#f09b57'
    - '#4f4434'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
